image:
  name: "danielebra/sep-ss:1.0"

before_script:
  - echo $PWD
  - echo $CI_PROJECT_DIR/
  - mkdir -p $CI_PROJECT_DIR/upload
  
stages:
  - test

api_endpoints:
  stage: test
  script:
    - cd src/SSWebApp/
    - npm install
    - node server.js >> $CI_PROJECT_DIR/upload/server.log &
    - sleep 3
    - cd ../python
    - nosetests api_tests.py 2> &1 | tee $CI_PROJECT_DIR/upload/api_endpoints_test.results
  artifacts:
    paths:
      - $CI_PROJECT_DIR/upload
    expire_in: 30 days
node:
  stage: test
  only:
    - master
  script:
    - cd src/SSWebApp/
    - node test.js
    - echo "Done node unit testing"