image:
  name: "node:latest"

before_script:
  - echo "Before script"
  
stages:
  - test
  - python

test:
  stage: test
  only:
    - master
  script:
    - cd src/SSWebApp/
    - node test.js
    - echo "Done node unit testing"
python:
  stage: python
  only:
    - master
  script:
    - apt update
    - apt install python-pip
    - pip install nose
    - cd src/SSWebApp/
    - npm install
    - npm run server &
    - cd ../python
    - nosetests api_tests.py
    