image:
  name: "danielebra/sep-ss:1.1"

before_script:
  - mkdir -p ~/upload
  
stages:
  - test
  - python

test:
  stage: test
  only:
    - master
  script:
    - cd src/SSWebApp/
    - node test.js
    - echo "Done node unit testing"
python:
  stage: python
  only:
    - master
  script:
    - cd src/SSWebApp/
    - node server.js >> ~/upload/server.log &
    - sleep 3
    - cd ../python
    - nosetests api_tests.py | tee >> ~/upload/test.results
  artifacts:
    paths:
      - ~/upload
    expire_in: 30 days
    