image:
  name: "danielebra/sep-ss:1.0"

before_script:
  - mkdir -p ~/upload
  
stages:
  - test

api_endpoints:
  stage: test
  script:
    - cd src/SSWebApp/
    - npm install
    - node server.js >> ~/upload/server.log &
    - sleep 3
    - cd ../python
    - nosetests api_tests.py | tee >> ~/upload/api_endpoints_test.results
  artifacts:
    paths:
      - ~/upload/
    expire_in: 30 days
node:
  stage: test
  only:
    - master
  script:
    - cd src/SSWebApp/
    - node test.js
    - echo "Done node unit testing"